// <auto-generated />
using System;
using Bissoft.Interview.Data;
using Bissoft.Interview.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bissoft.Interview.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Bissoft.Interview.Data.Entities.AnimalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<AType>("AnimalType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DateOfBirth");

                    b.Property<int>("ZooKeeperId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZooKeeperId");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Bissoft.Interview.Data.Entities.ZooKeeperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ZooKeeper");
                });

            modelBuilder.Entity("Bissoft.Interview.Data.Entities.AnimalEntity", b =>
                {
                    b.HasOne("Bissoft.Interview.Data.Entities.ZooKeeperEntity", "ZooKeeper")
                        .WithMany("Animals")
                        .HasForeignKey("ZooKeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZooKeeper");
                });

            modelBuilder.Entity("Bissoft.Interview.Data.Entities.ZooKeeperEntity", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
